[package]
name = "htl3r-da"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Julian Burger <https://github.com/cauvmou>"]
license = "CC-BY-4.0"
description = "HTL-Rennweg diploma thesis template."
homepage = "https://www.htlrennweg.at"
keywords = ["Diplomarbeit", "thesis", "diploma", "HTL Rennweg", "htl3r", "wien"]
categories = ["thesis"]
